### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by till** [alexdglover/jsonnet-render#5]
Hey,

I made a PR #4 to fix the README, in addition, I noticed that a run may error but the action completes as success:

```
RUNTIME ERROR: undefined external variable: TRAEFIK_BASIC_AUTH_USERS
	stack.jsonnet:6[9](https://github.com/foo/bar/runs/6574841156?check_suite_focus=true#step:5:10):62-[10](https://github.com/foo/bar/runs/6574841156?check_suite_focus=true#step:5:11)0	thunk <array_element>
	stack.jsonnet:2:11-17	object <anonymous>
	stack.jsonnet:(65:15)-(86:8)	object <anonymous>
	stack.jsonnet:(45:22)-(88:6)	object <anonymous>
	stack.jsonnet:(44:[13](https://github.com/foo/bar/runs/6574841156?check_suite_focus=true#step:5:14))-(179:4)	object <anonymous>
	During manifestation
```

**Comment by alexdglover** [comment]
solved via #4 , thanks for the contribution

**Comment by till** [comment]
Not sure if the second thing is fixed. 😅

**Comment by till** [comment]
@alexdglover check `entrypoint.sh`

Line 37 on. It misses a check `$?`. Without that, it will always complete successfully even when `jsonnet` errors.

**Comment by alexdglover** [comment]
This is quite old and don't think the line numbers match up anymore, but I did a quick test and wasn't able to repro locally.

```shell
$ INPUT_FILE=doesnt-exist INPUT_OUTPUT_FILE=doesnt-matter ./entrypoint.sh
Running jsonnet   doesnt-exist > doesnt-matter
Opening input file: doesnt-exist: no such file or directory
$ echo $?
1
```

It's also noteworthy that the output file isn't written to, meaning it isn't getting to [this line](https://github.com/alexdglover/jsonnet-render/blob/master/entrypoint.sh#L44). This indicates that the BASH script is doing a hard-exit on command failure, which makes sense because of the `-e` flag at the top of the script (see [docs on the -e flag](https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#The-Set-Builtin)).

I could be missing something, I only tested the script and not the entire GH Action. Please let me know if you're still seeing issues where Jsonnet errors aren't being surfaced as non-zero exit codes.
